feat: initial service and testing
School-TestExam/services-identity pull request #5
Opened 2024-05-27 18:24 UTC by HCeption

2024-05-28 08:49 UTC, Greboh requested changes

2024-05-28 08:49 UTC, Greboh commented on Exam.Services.Identity.IntegrationTests/Controller/IdentityControllerTests.cs
> +    //[Fact]
Fjern dette som er kommenteret ud :)

2024-05-28 08:49 UTC, Greboh commented on Exam.Services.Identity.IntegrationTests/Exam.Services.Identity.IntegrationTests.csproj
> +        <RootNamespace>Exam.Services.Identity.IntegrationTests</RootNamespace>
Fjerne RootNameSpace linjen. Den er ik nødvendig :)

2024-05-28 08:49 UTC, Greboh commented on Exam.Services.Identity.UnitTests/Exam.Services.Identity.UnitTests.csproj
> +  <PropertyGroup>
Tilføj dette
```
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
```

2024-05-28 08:49 UTC, Greboh commented on Exam.Services.Identity.UnitTests/Services/IdentityServiceTests.cs
> +        public async Task Create_NoCreatedByData_CreatesIdentityAsSystem()
Metode navngivning burde være eksempelvist 
[Action]_[State]_[ExpectedBehaviour]
Så eksempelvist
Create_ValidRequest_SavesEntityInDatabase

2024-05-28 08:49 UTC, Greboh commented on Exam.Services.Identity.UnitTests/Services/IdentityServiceTests.cs
Der skal være væsentligt flere tests for at opnå en ok branch rate.
Er det fordi, at alle cruds ik er lavet endnu?

2024-05-28 08:49 UTC, Greboh commented on Exam.Services.Identity.UnitTests/TestBase.cs
Jeg får lige lavet i Tools packagen, så der bare kan nedarves til at opsætte dette

2024-05-28 08:49 UTC, Greboh commented on School.Models.Identity/Entity/Identity.cs
Tom fil

2024-05-28 08:49 UTC, Greboh commented on School.Services.Identity/Controllers/IdentityController.cs
> +        public IdentityController(IIdentityService userService)
Det er ikke en userService. Så det giver bedre mening med enten service eller identityService

2024-05-28 08:49 UTC, Greboh commented on School.Services.Identity/Controllers/IdentityController.cs
> +            return dto is null ? NotFound() : Ok(dto);
Jeg foretrækker at lave validation enten med FluentValidations eller at gøre det inde i service laget. Så man holder controlleren relativ logik ren. Hvad tænker du?

2024-05-28 08:49 UTC, Greboh commented on School.Services.Identity/Services/IdentityService.cs
> +                return null;
Eventuelt kast en Exception her i stedet for at return null

2024-05-28 08:49 UTC, Greboh commented on School.Services.Identity/Services/IdentityService.cs
> +        //public async Task<IdentityDTO> Get(Guid id)
Slet

2024-05-28 12:30 UTC, HCeption commented on School.Services.Identity/Services/IdentityService.cs
> +                return null;
Selv med Exception test koden lukkede den servicen uden at lave vores Assert på en exception. Garanteret fejl.
Derfor ændrede jeg til at returne null
var act = async () => await Client.PutAsJsonAsync(url, request);
await act.Should().ThrowAsync<Exception>();

2024-05-28 12:35 UTC, HCeption commented on School.Services.Identity/Controllers/IdentityController.cs
> +            return dto is null ? NotFound() : Ok(dto);
Duplicate fra anden comment:
Selv med Exception test koden lukkede den servicen uden at lave vores Assert på en exception. Garanteret fejl.
Derfor ændrede jeg til at returne null

Assert koden som aldrig kom til assert delen:
var act = async () => await Client.PutAsJsonAsync(url, request);
await act.Should().ThrowAsync();

2024-05-28 12:50 UTC, HCeption commented on School.Services.Identity/Services/IdentityService.cs
> +                return null;
Hmm. Exception testing virker dog i Unit testing, men ikke min Integration testing...

Ill keep searching...

2024-05-28 15:57 UTC, Greboh commented on School.Services.Identity/Services/IdentityService.cs
> +                return null;
Har tilføjet til core. Eksempel:

Service:
```
        public async Task<IdentityDTO> Get(Guid id)
        {
            var entity = await _context.Identities.FirstOrDefaultAsync(x => x.Id == id);

            if (entity is null)
            {
                throw new NotFoundException($"Couldn't find entity with id: {id}");
            }
            
            return entity.Adapt<IdentityDTO>();
        }
```
Controller:
```
 [HttpGet("{id:guid}")]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [ProducesResponseType(typeof(IdentityDTO), StatusCodes.Status200OK)]
        public async Task<ActionResult<IdentityDTO>> Get([FromRoute] Guid id)
        {
            var dto = await _service.Get(id);

            return Ok(dto);
        }
```
Test:
```
    [Fact]
    public async Task Get_EntityDoesntExist_ThrowsException()
    {
        // Arrange
        var id = Guid.NewGuid();

        // Act
        var response = await Client.GetAsync($"{_basePath}/{id}");

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.NotFound);
    }
```

2024-05-29 18:40 UTC, Greboh commented on Exam.Services.Identity/Exam.Services.Identity.csproj
> +      <PackageReference Include="Exam.Core" Version="0.0.3-rc03-feature-6-create-exceptionfilter" />
Skal opdateres til release og ikke rc 😊

2024-05-30 11:47 UTC, HCeption commented on Exam.Services.Identity/Exam.Services.Identity.csproj
> +      <PackageReference Include="Exam.Core" Version="0.0.3-rc03-feature-6-create-exceptionfilter" />
Den burde allerede være fikset.
Commit  "fix: nuget update"

2024-05-30 12:22 UTC, Greboh approved these changes

2024-05-30 12:23 UTC, merged